
FROM rust:1.85 as builder

RUN apt-get update && apt-get install -y pkg-config libssl-dev

WORKDIR /app

COPY . .

RUN cargo build --release --features jemalloc

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/todo_app /usr/local/bin/todo_app
COPY --from=builder /app/config ./config

CMD ["todo_app"]