services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards # *.json dashboard files
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards # dashboards.yml
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources # datasources.yml
    networks:
      - axum_net
    depends_on:
      - otel-collector
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - axum_net

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/tempo-data:/tmp/tempo/blocks
      - ./tempo/tempo-wal:/tmp/tempo/wal
    command: ["-config.file=/etc/tempo.yaml", "-target=all"] # monolithic mode
    networks:
      - axum_net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"     # OTLP gRPC for metrics
      - "8888:8888"     # Metrics self monitoring
      - "9464:9464"     # Prometheus metrics exporter
    networks:
      - axum_net
    depends_on:
      - tempo


networks:
  axum_net:
    driver: bridge
    external: true

volumes:
  grafana-data:
  tempo-data:
