global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
  - job_name: 'win-exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']
  - job_name: 'k6'
    static_configs:
      - targets: ['k6:5656']
