{
 "title": "auth",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "hash_p50_p90_p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(password_hash_duration_milliseconds_bucket[30s]))",
     "legendFormat": "{{algorithm}}-p50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(password_hash_duration_milliseconds_bucket[30s]))",
     "legendFormat": "{{algorithm}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(password_hash_duration_milliseconds_bucket[30s]))",
     "legendFormat": "{{algorithm}}-p99"
    }
   ]
  },
  {
   "title": "hash_p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(password_hash_duration_milliseconds_bucket[30s]))",
     "legendFormat": "{{algorithm}}"
    },
    {
     "expr": "avg_over_time(\r\n  histogram_quantile(0.95, rate(password_hash_duration_milliseconds_bucket[1m]))\r\n  [2m:15s]\r\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "hash_SLO_250ms_%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(password_hash_duration_milliseconds_bucket{le=\"250.0\"}[30s])) / sum(rate(password_hash_duration_milliseconds_count[30s])) * 100",
     "legendFormat": "%"
    },
    {
     "expr": "sum(rate(k6_http_reqs{phase=\"bench\"}[30s]))",
     "legendFormat": "phase-bench"
    },
    {
     "expr": "sum(rate(k6_http_reqs{phase=\"warmup\"}[30s]))",
     "legendFormat": "phase-warmup"
    }
   ]
  },
  {
   "title": "verify_p50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(password_verify_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "verify_p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(password_verify_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "verify_p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(password_verify_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "total_auth_requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_requests_total{uri=~\"/auth/(register|login)\"}[30s])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}