{
 "title": "k6 bench",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "phase", "label": "Phase", "query": { "query": "label_values(phase)" } }
  ]
 },
 "panels": [
  {
   "title": "p50 / p90 / p99 ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_duration{quantile=\"0.5\", phase=\"$phase\"}",
     "legendFormat": "p50 {{phase}}"
    },
    {
     "expr": "k6_http_req_duration{quantile=\"0.9\", phase=\"$phase\"}",
     "legendFormat": "p90  {{phase}}"
    },
    {
     "expr": "k6_http_req_duration{quantile=\"1.0\", phase=\"$phase\"}",
     "legendFormat": "p100  {{phase}}"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_duration{quantile=\"0.95\", phase=\"$phase\"}",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(k6_http_reqs{phase=\"$phase\"}[30s])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "VUs vs RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "k6_vus" },
    {
     "expr": "rate(k6_http_reqs{phase = \"$phase\"}[30s])",
     "legendFormat": "rps {{phase}}"
    }
   ]
  },
  {
   "title": "Active VUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "vus" }
   ]
  },
  {
   "title": "Data out / in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kB/s" } },
   "targets": [
    {
     "expr": "rate(k6_data_sent{phase=\"$phase\"}[30s])",
     "legendFormat": "out {{phase}}"
    },
    {
     "expr": "rate(k6_data_received{phase=\"$phase\"}[30s])",
     "legendFormat": "in {{phase}}"
    }
   ]
  },
  {
   "title": "Iterations / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(k6_iterations{phase=\"$phase\"}[30s])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_req_failed_sum{phase=\"$phase\"}[30s])) / sum(rate(k6_http_reqs{phase=\"$phase\"}[30s])) * 100",
     "legendFormat": "error % {{phase}}"
    }
   ]
  },
  {
   "title": "Failed checks %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "(rate(k6_checks_count{phase=\"$phase\"}[1m]) - rate(k6_checks_sum{phase=\"$phase\"}[1m])) / rate(k6_checks_count{phase=\"$phase\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}