name: check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check
  clippy:
      runs-on: ubuntu-latest
      name: ${{ matrix.toolchain }} / clippy
      permissions:
        contents: read
        checks: write
      strategy:
        fail-fast: false
        matrix:
          # Get early warning of new lints which are regularly introduced in beta channels.
          toolchain: [stable, beta]
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: Install ${{ matrix.toolchain }}
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: ${{ matrix.toolchain }}
            components: clippy
        - name: Run Clippy
          run: cargo clippy --all-targets --features jemalloc -- -D warnings
  doc:
      # run docs generation on nightly rather than stable. This enables features like
      # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html which allows an
      # API be documented as only available in some specific platforms.
      runs-on: ubuntu-latest
      name: nightly / doc
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: Install nightly
          uses: dtolnay/rust-toolchain@nightly
        - name: Install cargo-docs-rs
          uses: dtolnay/install@cargo-docs-rs
        - name: cargo docs-rs
          run: cargo docs-rs
